[theme]

# Primary accent for interactive elements
primaryColor = '#0074B7'

# Background color for the main content area
backgroundColor = '#F6F8FB'


# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#EEF2F8'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "serif"